---
- name: echo 'hello world'
  command: echo "Hello {{ world }}"
  register: result

- name: print message
  debug:
    msg: "{{ result.stdout_lines }}"

- name: Update apt-get cache
  apt: >
    update_cache=yes
  become: true
  become_user: root
    
- name: Update all packages to the latest version
  apt: > 
    upgrade=yes
  become: true
  become_user: root

- name: set timezone to Europe/Amsterdam
  timezone:
    name: Europe/Amsterdam
  become: true
  become_user: root

