---
- include_vars: ../vars/vault.yml

- name: Update apt-get cache
  apt: >
    update_cache=yes
    cache_valid_time=3600
  become: true
  become_user: root

- name: install packages
  apt:
    name="{{item}}"
    update_cache=yes
    state=latest
  with_items:
  - python3-pip
  become: true
  become_user: root

- name: pip3 install psutil
  command: pip3 install psutil
  args:
    creates: /usr/local/lib/python3.5/dist-packages/psutil
  become: true
  become_user: root

- name: mkdir root/slack
  file:
    path: /home/pi/node_programs/root/slack
    state: directory
    mode: 0755

- name: Copy slack.py
  copy:
    src: ../files/slack.py
    dest: /home/pi/node_programs/root/slack/slack.py
    mode: 0755

- name: insert secret in /home/pi/node_programs/root/slack/slack.py
  replace:
    path: /home/pi/node_programs/root/slack/slack.py
    regexp: '{{SlackClient}}'
    replace: "{{ SlackClient }}"

- name: Copy slack_del.py
  copy:
    src: ../files/slack_del.py
    dest: /home/pi/node_programs/root/slack/slack_del.py
    mode: 0755

- name: insert secret in /home/pi/node_programs/root/slack/slack_del.py
  replace:
    path: /home/pi/node_programs/root/slack/slack_del.py
    regexp: '{{SlackClient}}'
    replace: "{{ SlackClient }}"

- name: New node project
  copy:
    src: ../files/package.json
    dest: /home/pi/node_programs/root/slack/package.json
    mode: 0755

- name: npm install pm2
  command: npm install pm2 -g
  args:
    chdir: /home/pi/node_programs/root/
    creates: /usr/local/lib/node_modules/pm2
  become: true
  become_user: root

- name: npm install
  command: npm install --save
  args:
    chdir: /home/pi/node_programs/root/slack/
    creates: /home/pi/node_programs/root/slack/node_modules

- name: Copy index.js
  copy:
    src: ../files/index.js
    dest: /home/pi/node_programs/root/slack/index.js
    mode: 0755

- name: Copy index.html
  copy:
    src: ../files/index.html
    dest: /home/pi/node_programs/root/slack/index.html
    mode: 0755

- name: Check if port 8081 is listening
  wait_for:
    port: 8081
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 8081 to respond"
  register: port_check
  ignore_errors: yes

- name: start Node
  shell: "pm2 start /home/pi/node_programs/root/slack/index.js"
  args:
    chdir: /home/pi/node_programs/root/slack
  async: 1000
  poll: 0
  when: port_check.failed == true
  become: true
  become_user: root

