- name: Update apt-get cache
  apt: >
    update_cache=yes
  become: true
  become_user: root

- name: install packages
  apt: 
    name="{{item}}" 
    update_cache=yes 
    state=latest
  with_items:
  - nodejs 
  - npm 
  - node-semver
  become: true
  become_user: root
