- name: Unarchive node.js
  unarchive:
    src: https://nodejs.org/dist/v6.2.1/node-v6.2.1-linux-armv6l.tar.gz
    dest: /home/pi
    remote_src: yes
  become: true
  become_user: root

- name: copy node file
  copy:
    src: /home/pi/node-v6.2.1-linux-armv6l/bin/node
    dest: /usr/bin
    mode: 0755
  become: true
  become_user: root

- name: copy npm file
  copy:
    src: /home/pi/node-v6.2.1-linux-armv6l/bin/npm
    dest: /usr/bin
    mode: 0755
  become: true
  become_user: root

