- name: Update apt-get cache
  apt: >
    update_cache=yes
    cache_valid_time=3600
  become: true
  become_user: root

- name: install packages
  apt: 
    name="{{item}}" 
    update_cache=yes 
    state=latest
  with_items:
  - nodejs 
  - npm 
  - node-semver
  become: true
  become_user: root

- name: ln node to nodejs
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
  become: true
  become_user: root

- name: mkdir node_programs/root
  file:
    path: /home/pi/node_programs/root
    state: directory
    mode: 0755

- name: New node project
  copy:
    src: ../files/package.json
    dest: /home/pi/node_programs/package.json
    mode: 0755

- name: Copy index.js
  copy:
    src: ../files/index.js
    dest: /home/pi/node_programs/index.js
    mode: 0755

- name: Copy index.html
  copy:
    src: ../files/index.html
    dest: /home/pi/node_programs/index.html
    mode: 0755

- name: npm install express
  command: npm install express --save
  args:
    chdir: /home/pi/node_programs
    creates: /home/pi/node_programs/node_modules/express

- name: npm install pm2
  command: npm install pm2 -g 
  args:
    chdir: /home/pi/node_programs/root/
    creates: /usr/local/lib/node_modules/pm2
  become: true
  become_user: root

- name: npm install handlebars
  command: npm install handlebars -save
  args:
    chdir: /home/pi/node_programs/root/
    creates: /home/pi/node_programs/node_modules/handlebars
  
- name: Check if node is running
  wait_for:
    port: 80
    delay: 5
    timeout: 10
    msg: "Timeout waiting for node to respond"
  register: port_check
  ignore_errors: yes

- name: start Node
  shell: "pm2 start /home/pi/node_programs/index.js "
  args:
    chdir: /home/pi/node_programs/
  async: 1000
  poll: 0
  when: port_check.failed == true
  become: true
  become_user: root
