---
- name: Update apt-get cache
  apt: >
    update_cache=yes
    cache_valid_time=3600
  become: true
  become_user: root

- name: install packages
  apt:
    name="{{item}}"
    update_cache=yes
    state=latest
  with_items:
  - build-essential 
  - python-dev
  become: true
  become_user: root

- name: Extract Adafruit_Python_DHT.tar.gz
  unarchive:
    src: Adafruit_Python_DHT.tar.gz
    dest: /home/pi

- name: install Adafruit_Python_DHT
  shell: python setup.py install
  args:
    chdir: /home/pi/Adafruit_Python_DHT
    creates: /usr/local/lib/python2.7/dist-packages/Adafruit_DHT-1.3.2-py2.7-linux-armv6l.egg
  become: true
  become_user: root

- name: Copy dht.py
  copy:
    src: ../files/dht.py
    dest: /home/pi/dht.py
    mode: 0755

- name: Test temperature
  shell: python /home/pi/dht.py
  args:
    chdir: /home/pi/
  register: result

- name: print message
  debug:
    msg: "{{ result.stdout_lines }}"

- name: Install node-dht-sensor node.js package.
  npm:
    name="{{item}}"
  with_items:
  - node-dht-sensor
  - request
  become: true
  become_user: root

- name: mkdir sensor
  file:
    path: /home/pi/node_programs/sensor
    state: directory
    mode: 0755

- name: New node project
  copy:
    src: ../files/package.json
    dest: /home/pi/node_programs/sensor/package.json
    mode: 0755

- name: Copy server.js
  copy:
    src: ../files/server.js
    dest: /home/pi/node_programs/sensor/server.js
    mode: 0755

- name: Copy server.html
  copy:
    src: ../files/server.html
    dest: /home/pi/node_programs/sensor/server.js
    mode: 0755

