---
- name: Update apt-get cache
  apt: >
    update_cache=yes
    cache_valid_time=3600
  become: true
  become_user: root

- name: install packages
  apt:
    name="{{item}}"
    update_cache=yes
    state=latest
  with_items:
  - build-essential 
  - python-dev
  become: true
  become_user: root

- name: Extract Adafruit_Python_DHT.tar.gz
  unarchive:
    src: Adafruit_Python_DHT.tar.gz
    dest: /home/pi

- name: install Adafruit_Python_DHT
  shell: python setup.py install
  args:
    chdir: /home/pi/Adafruit_Python_DHT
    creates: /usr/local/lib/python2.7/dist-packages/Adafruit_DHT-1.3.2-py2.7-linux-armv6l.egg
  become: true
  become_user: root

- name: mkdir root/sensor
  file:
    path: /home/pi/node_programs/root/sensor
    state: directory
    mode: 0755

- name: Copy dht.py
  copy:
    src: ../files/dht.py
    dest: /home/pi/node_programs/root/sensor/dht.py
    mode: 0755

- name: New node project
  copy:
    src: ../files/package.json
    dest: /home/pi/node_programs/root/sensor/package.json
    mode: 0755

- name: npm install
  command: npm install --save
  args:
    chdir: /home/pi/node_programs/root/sensor/
    creates: /home/pi/node_programs/root/sensor/node_modules
  become: true
  become_user: root

- name: install npm node-dht-sensor request --save
  command: npm install node-dht-sensor request --save
  args:
    chdir: /home/pi/node_programs/root/sensor/
    creates: /home/pi/node_programs/root/sensor/node_modules/node-dht-sensor
  become: true
  become_user: root

- name: Copy index.js
  copy:
    src: ../files/index.js
    dest: /home/pi/node_programs/root/sensor/index.js
    mode: 0755

- name: Copy index.html
  copy:
    src: ../files/index.html
    dest: /home/pi/node_programs/root/sensor/index.js
    mode: 0755

- name: Check if port 8080 is listening
  wait_for:
    port: 8080
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 8080 to respond"
  register: port_check
  ignore_errors: yes

- name: start Node
  shell: nodejs index.js
  args:
    chdir: /home/pi/node_programs/root/sensor
  async: 1000
  poll: 0
  when: port_check.failed == true
  become: true
  become_user: root
