- name: enable camera
  command: raspi-config nonint do_camera 0
  become: true
  become_user: root

- name: mkdir liveStreaming
  file:
    path: /home/pi/node_programs/liveStreaming
    state: directory
    mode: 0755

- name: New node project
  copy:
    src: ../files/package.json
    dest: /home/pi/node_programs/liveStreaming/package.json
    mode: 0755

- name: Copy index.js
  copy:
    src: ../files/index.js
    dest: /home/pi/node_programs/liveStreaming/index.js
    mode: 0755

- name: Copy index.html
  copy:
    src: ../files/index.html
    dest: /home/pi/node_programs/liveStreaming/index.html
    mode: 0755

- name: install express socket.io --save
  command: npm install express socket.io --save
  args:
    chdir: /home/pi/node_programs/liveStreaming
    creates: /home/pi/node_programs/liveStreaming/node_modules

  
